spring:
  application:
    name: fm-zuul
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  # 服务路由
  routes:
    fm-user: /user/**
    fm-order: /order/**