spring:
  application:
    name: fm-user
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/